#!/bin/sh
#
# $Id$
# This file should not be modified
#
# This script is run by the pppd after the link is established.
#
# This script is called with the following arguments:
#    Arg  Name                          Example
#    $1   Interface name                ppp0
#    $2   The tty                       ttyS1
#    $3   The link speed                38400
#    $4   Local IP number               12.34.56.78
#    $5   Peer  IP number               12.34.56.99
#    $6   Optional ``ipparam'' value    foo

set +e

# The  environment is cleared before executing this script
# so the path must be reset
PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
export PATH
# These variables are for the use of the scripts run by run-parts
PPP_IFACE="$1"
PPP_TTY="$2"
PPP_SPEED="$3"
PPP_LOCAL="$4"
PPP_REMOTE="$5"
PPP_IPPARAM="$6"
export PPP_IFACE PPP_TTY PPP_SPEED PPP_LOCAL PPP_REMOTE PPP_IPPARAM

. /etc/rc.d/init.d/functions 
. /etc/sysconfig/network-scripts/functions.network 
CONFIG="$PPP_IPPARAM"
source_config

# as an additional convenience, $PPP_TTYNAME is set to the tty name,
# stripped of /dev/ (if present) for easier matching.
PPP_TTYNAME=$(basename "$PPP_TTY")
export PPP_TTYNAME

# Main Script starts here
[ -x /etc/ppp/ip-up.local ] && /etc/ppp/ip-up.local

run-parts /etc/sysconfig/interfaces/up.d/ppp

/etc/sysconfig/network-scripts/ifup-post "$CONFIG"

exit 0
