#!/bin/sh
#
#	$Id: setsysfont,v 1.5.2.1 2000/10/18 20:10:45 misiek Exp $
#

[ -f /etc/sysconfig/i18n ] && . /etc/sysconfig/i18n
[ -f /etc/sysconfig/console ] && . /etc/sysconfig/console

if [ -x /usr/bin/consolechars -o -x /bin/consolechars ]; then
	if [ -n "$SYSFONT" ]; then
		consolechars -f $SYSFONT
	elif [ -n "$CONSOLEFONT" ]; then
		consolechars -m ${CONSOLEMAP:-trivial.trans} -f $CONSOLEFONT
	fi
	if [ -n "$KEYTABLE" ]; then
		loadkeys $KEYTABLE < /dev/tty0 > /dev/tty0
	fi


elif [ -x /usr/bin/setfont ]; then
	if [ -n "$SYSFONT" ]; then
		/usr/bin/setfont $SYSFONT
	fi
else
	echo "can't set font"
	exit 1
fi
