#!/bin/sh
#
#	$Id: setsysfont,v 1.3 1999/07/13 12:49:34 misiek Exp $
#

if [ -f /etc/sysconfig/i18n ]; then
  . /etc/sysconfig/i18n
fi

if [ -x /usr/bin/consolechars ]; then
  if [ -n "$SYSFONT" ]; then
  /usr/bin/consolechars -f $SYSFONT
  fi
elif [ -x /usr/bin/setfont ]; then
  if [ -n "$SYSFONT" ]; then
    /usr/bin/setfont $SYSFONT
  fi
else
  echo "can't set font"
  exit 1
fi
