#!/bin/sh
# $Id: logger,v 1.1 2000/05/07 19:00:06 siefca Exp $
# You can put here anything :)
#
echo "+---------------------------------------------------------------+" >> /var/log/ppp.log
echo " Connect time: `date` with $PPP_REMOTE                    " >> /var/log/ppp.log
