#!/bin/sh
#
#	$Id: ifdown-ppp,v 1.9 2000/04/21 17:44:22 jajcus Exp $
#
PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /etc/sysconfig/network
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network-scripts/.functions

CONFIG=$1
source_config

if [ ! -f /var/run/ppp-$DEVICE.pid ]; then
    # ppp isn't running, or we didn't start it
    exit 0
fi

get_ppp_device_and_pid

if [ -z "$PID" ]; then
  exit 1
fi

rm -f /var/run/ppp-$DEVICE.pid

# pppd might have chat as a child; remember chat's pid to kill after pppd.
# (After, not before, so that pppd doesn't just restart it).

CHATPID=`ps axl | awk '$4 ~ /^'"$PID"'$/ {print $3}' 2>/dev/null`

kill $PID > /dev/null 2>&1
[ -n "$CHATPID" ] && kill $CHATPID > /dev/null 2>&1
if [ ! -d /proc/$PID ]; then
  /etc/sysconfig/network-scripts/ifdown-post $1
  exit 0
fi
sleep 2
if [ ! -d /proc/$PID ]; then
  /etc/sysconfig/network-scripts/ifdown-post $1
  exit 0
fi

kill -KILL $PID > /dev/null 2>&1
if [ -d /proc/$PID ]; then
  logger -p daemon.info -t ifdown-ppp "ifdown-ppp unable to kill pppd-$DEVICE" &
else
  /etc/sysconfig/network-scripts/ifdown-post $1
fi

exit 1
