#!/bin/sh
#
#    ifdown-lec - ATM LANE interfaces configuration script
#    Copyright (C) 1999, 2000 Robert ¦laski <robin@atm.com.pl>
#    Copyright (C) 2000 Arkadiusz Mi¶kiewicz <misiek@pld.org.pl>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#    $Id: ifdown-lec,v 1.1.2.2 2001/09/30 10:19:42 misiek Exp $
#

. /etc/sysconfig/network
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network-scripts/functions.network

DEV=$1

[ -z "$DEV" ] && {
    nls "usage: %s <device name>" ifup-lec >&2
    exit 1
}

. /etc/sysconfig/network
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network-scripts/functions.network

if [ -r /etc/sysconfig/atm ]; then
	. /etc/sysconfig/atm
else
	exit 0
fi

if is_no "$LANE"; then
	exit 0
fi

if [ -f "/etc/sysconfig/interfaces/ifcfg-$DEV" ] ; then
        CONFIG="/etc/sysconfig/interfaces/ifcfg-$DEV"
else
        CONFIG="$DEV"
fi
		
source_config

if [ "foo$2" = "fooboot" ] && is_no "${ONBOOT}"; then
        exit
fi

if [ ! -f /var/run/zeppelin-$DEVICE.pid ]; then
    nls "zeppelin %s isn't running, or we didn't start it" "$DEVICE"
    exit 0
fi

PID=$(cat /var/run/zeppelin-$DEVICE.pid)
[ -z "$PID" ] && exit 1

kill -TERM $PID >/dev/null 2>&1
sleep 1
[ -d /proc/$PID ] && kill -KILL $PID > /dev/null 2>&1

rm -f "/var/run/zeppelin-$DEVICE.pid"
	
# This must be last line !
# vi:syntax=sh:tw=78:ts=8:sw=4

