#!/bin/sh
#
#	$Id$
#
PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /etc/sysconfig/network
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network-scripts/functions.network

CONFIG=$1
source_config

if [ ! -f /var/run/ppp-$DEVNAME.pid ]; then
    # ppp isn't running, or we didn't start it
    exit 0
fi

# set all major variables
setup_ip_param
get_ppp_device_and_pid

if [ -z "$PID" ]; then
    exit 1
fi

rm -f /var/run/ppp-$DEVNAME.pid

[ ! -d /proc/${PID} ] && exit 0

kill -TERM ${PID} > /dev/null 2>&1

sleep 2
[ -d /proc/${PID} ] && sleep 2 && [ -d /proc/${PID} ] && sleep 5

kill -KILL ${PID} > /dev/null 2>&1
logger -p daemon.info -t ifdown-ppp "ifdown-ppp unable to nicely kill pppd-$DEVICE (pppd-$DEVNAME)" &

/etc/sysconfig/network-scripts/ifdown-post $1

exit 1

# This must be last line !
# vi:syntax=sh:tw=78:ts=8:sw=4

