#!/bin/sh
#
#    ifdown-vlan - Virtual LAN configuration script
#    Copyright (C) 2001 Arkadiusz Miśkiewicz <misiek@pld-linux.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#    $Id$
#
PATH=/sbin:/usr/sbin:/bin:/usr/bin

cd /etc/sysconfig/network-scripts
. /etc/sysconfig/network
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network-scripts/functions.network

CONFIG=$1
source_config

if [ "foo$2" = "fooboot" ] && is_no "${ONBOOT}"; then
	exit 0
fi

# set all major variables
setup_ip_param

ip link set ${DEVICE} down
LC_ALL=C ip addr flush dev ${DEVICE} 2>&1 | grep -v "Nothing to flush"

if LC_ALL=C ip link help 2>&1 | grep -q del; then
	/sbin/ip link del ${DEVICE}
elif [ -x /sbin/vconfig ]; then
	/sbin/vconfig rem ${DEVICE}
else
	nls "/sbin/vconfig or iproute2 with vlan support is missing. Can't continue."
	exit 1
fi

RESULT=$?

exit $RESULT
