#!/bin/sh
#
#	$Id: ifdown,v 1.9 1999/07/31 11:24:20 misiek Exp $
#
PATH=/sbin:/usr/sbin:/bin:/usr/bin

cd /etc/sysconfig/network-scripts
. /etc/rc.d/init.d/functions.network

CONFIG=$1

[ -z "$CONFIG" ] && {
    echo "usage: ifdown <device name>" >&2
    exit 1
}

[ -f "/etc/sysconfig/interfaces/$CONFIG" ] || CONFIG=ifcfg-$CONFIG
[ -f "/etc/sysconfig/interfaces/$CONFIG" ] || {
    echo "usage: ifdown <device name>" >&2
    exit 1
}

if [ `id -u` != 0 ]; then
    if [ -x /usr/sbin/usernetctl ]; then
        exec /usr/sbin/usernetctl $CONFIG down
    fi
    echo "Users cannot control this device." >&2
    exit 1
fi

source_config

# Is interface IPv6 only ?
[ -z "$IPADDR" -a "$PUMP" != "true" ] && IPv6_ONLY=yes || IPv6_ONLY=""

if [ -z "$IPv6_ONLY" ]; then
  if [ -z "$PREFIX" ] && [ -n "$NETMASK" ]; then
    PREFIX="`calcprefix $NETMASK`"
  fi

  if [ -z "$NETMASK" ] && [ -n "$PREFIX" ]; then
    NETMASK="`calcnetmask $PREFIX`"
  fi
fi

FULLDEVNAME="$DEVICE"
DEVICETYPE=`echo $FULLDEVNAME | sed "s/[0-9]*$//"`
DEVICE=`echo $FULLDEVNAME | sed 's/:.*//g'`
OTHERSCRIPT="/etc/sysconfig/network-scripts/ifdown-${DEVICETYPE}"

if [ -x $OTHERSCRIPT -a -z "$IPv6_ONLY" ]; then
	$OTHERSCRIPT $CONFIG $2
	exit $?
fi

if echo "$FULLDEVNAME" | grep -q ':' ; then
    ISALIAS=yes
else
    ISALIAS=no
fi

if [ "$ISALIAS" == "yes" ]; then
	if [ -z "$IPv6_ONLY" ]; then
		ip -family inet addr del ${IPADDR}/${PREFIX} dev ${DEVICE} label ${FULLDEVNAME}
	fi
		for ADDR in ${IPV6_ADDR} ; do
			ip -family inet6 addr del ${ADDR} dev ${DEVICE} label ${FULLDEVNAME}
		done
else
    ip link set ${DEVICE} down
    ip addr flush dev ${DEVICE} 2> /dev/null
fi


exec /etc/sysconfig/network-scripts/ifdown-post $CONFIG

