#!/bin/sh
#
#	$Id: ifdown-post,v 1.6 1999/07/13 12:49:37 misiek Exp $
#
# This should be called whenever an interface goes down, not just when
# it is brought down explicitly.

cd /etc/sysconfig/network-scripts

CONFIG=$1
. /etc/rc.d/init.d/functions.network
source_config

# Notify programs that have requested notification
do_netreport

exit 0
