#!/bin/sh
#
#    ifdown-br - bridge configuration script
#    Copyright (C) 2000 Arkadiusz Miśkiewicz <misiek@pld-linux.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#    $Id$
#
PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /etc/sysconfig/network
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network-scripts/functions.network

CONFIG=$1
source_config

if [ "foo$2" = "fooboot" ] && is_no "${ONBOOT}"; then
	exit
fi

if [ ! -x /sbin/brctl ]; then
	nls "%s is missing. Can't continue." "/sbin/brctl"
	exit 1
fi

# set all major variables
setup_ip_param

# set device down and forget all addresses
for device in ${BRIDGE_DEVS}; do
	ip addr flush dev ${device} 2>&1 | grep -v "Nothing to flush"
	ip link set ${device} down
	brctl delif ${DEVICE} ${device}
done

ip link set ${DEVICE} down
brctl delbr ${DEVICE}

# This must be last line !
# vi:syntax=sh
