#!/bin/sh
#
#	$Id: ifup-routes,v 1.4 1999/07/13 12:49:37 misiek Exp $
#
# adds static routes which go through device $1

if [ "$1" = "" ]; then
	echo "usage: $0 <net-device>"
	exit 1
fi

if [ ! -f /etc/sysconfig/static-routes ]; then
    exit 0
fi
#note the trailing space in the grep gets rid of aliases
grep "^$1 " /etc/sysconfig/static-routes | while read device args; do
    /sbin/ip route add $args dev $device
done
