#!/bin/sh

# adds aliases of device $1

if [ "$1" = "" ]; then
	echo "usage: $0 <net-device>"
	exit 1
fi

allow_null_glob_expansion=foo
for alias in /etc/sysconfig/network-scripts/ifcfg-$1:* ; do
    /etc/sysconfig/network-scripts/ifup $alias
done
unset allow_null_glob_expansion
