#!/bin/sh
#
#    ifup-atm - ATM CLIP interfaces configuration script
#    Copyright (C) 1999, 2000 Robert ¦laski <robin@atm.com.pl>
#    Copyright (C) 2000 Arkadiusz Mi¶kiewicz <misiek@pld.org.pl>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#    $Id: ifup-atm,v 1.1.2.1 2000/10/18 20:10:55 misiek Exp $
#

. /etc/sysconfig/network
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network-scripts/.functions

DEV=$1

[ -z "$DEV" ] && {
    nls "usage: %s <device name>" "ifup-atm" >&2
    exit 1
}

if [ -r /etc/sysconfig/atm ]; then
	. /etc/sysconfig/atm
else
	exit 0
fi

if is_no "$CLIP"; then
	exit 0
fi

if [ ! -x /sbin/atmarp ]; then
        nls "%s is missing. Can't continue." "/sbin/atmarp"
        exit 1
fi
		

if [ -f "/etc/sysconfig/interfaces/ifcfg-$DEV" ] ; then
        CONFIG="/etc/sysconfig/interfaces/ifcfg-$DEV"
else
        CONFIG="$DEV"
fi
		
source_config

if [ "foo$2" = "fooboot" ] && is_no "${ONBOOT}"; then
        exit
fi

# set all major variables
setup_ip_param

# check again in case of manuall interface starting
atm_daemons_start

INTERFACE=$(echo "$DEVICE" | awk ' { gsub(/^lec/,NIL); print $0 } ')

atmarp -c $INTERFACE
atmarp -s $ARPSRV_IPADDR $ARPSRV_ATMADDR arpsrv

# FIXME. Ask Robert about these. --misiek
#[ -z "$ARPDEFQOS" ] || atmarp -q $NETWORK $ARPDEFQOS
#[ -z "$ARPSRV" ] || atmarp -s $NETWORK $ARPSRV arpsrv \
#  `[ -z "$ARPSRVQOS" ] || echo qos $ARPSRVQOS`

# This must be last line !
# vi:syntax=sh:tw=78:ts=8:sw=4

