#!/bin/sh
#
#	$Id: ifup-sl,v 1.7 1999/07/13 12:49:37 misiek Exp $
#
PATH=/sbin:/usr/sbin:/bin:/usr/bin

# ifup-post can't be done for slip :-( Solution: use PPP

# become a daemon in case we have to persist.
if [ "$1" != daemon ] ; then
  # disconnect stdin, out, err to disassociate from controlling tty
  # so that no HUPs will get through.
  $0 daemon $*& </dev/null >/dev/null 2>/dev/null
  exit 0
fi
shift

cd /etc/sysconfig/network-scripts
. /etc/rc.d/init.d/functions.network

CONFIG=$1
source_config

if [ "foo$2" = "fooboot" -a ${ONBOOT} = "no" ]
then
  exit
fi

if [ -z "$RETRYTIMEOUT" ]; then
  RETRYTIMEOUT=30
fi

# we can use dip or direct slip connection via slattach
if [ "$DIRECT_CONNECT" != "yes" ]; then

[ -x /usr/sbin/dip ] || {
  echo "/usr/sbin/dip does not exist or is not executable"
  echo "ifup-sl for $DEVICE exiting"
  logger -p daemon.info -t ifup-sl \
    "/usr/sbin/dip does not exist or is not executable for $DEVICE"
  exit 1
}

DIPSCRIPT=/etc/sysconfig/network-scripts/dip-$DEVNAME
[ -f $DIPSCRIPT ] || {
  DIPSCRIPT=/etc/sysconfig/network-scripts/dip-$PARENTDEVNAME
}
[ -f $DIPSCRIPT ] || {
  echo "/etc/sysconfig/network-scripts/dip-$DEVICE does not exist"
  echo "ifup-sl for $DEVICE exiting"
  logger -p daemon.info -t ifup-sl \
    "/etc/sysconfig/network-scripts/dip-$DEVICE does not exist for $DEVICE"
  exit 1
}

while : ; do
  echo > /var/run/sl-$DEVICE.dev
  (logger -p daemon.info -t ifup-sl \
    "dip started for $DEVICE on $MODEMPORT at $LINESPEED" &)&
  doexec /usr/sbin/dip dip-$DEVICE $DIPSCRIPT
  if [ "$PERSIST" != "yes" -o ! -f /var/run/sl-$DEVICE.dev ] ; then
    exit 0
  fi
  rm -f /var/run/sl-$DEVICE.dev


  sleep $RETRYTIMEOUT || {
    # sleep was killed
    exit 0
  }
done

else
# direct connection via slattach
[ -z "$MTU" ] && MTU=1500
[ -z "$PROTOCOL" ] && PROTOCOL=slip

[ -x /sbin/slattach ] || {
	echo "/sbin/slattach does not exist or is not executable"
        echo "ifup-sl for $DEVICE exiting"
        logger -p daemon.info -t ifup-sl \
        "/sbin/slattach does not exist or is not executable for $DEVICE"
        exit 1
}

        echo > /var/run/sl-$DEVICE.dev
        (logger -p daemon.info -t ifup-sl \
        "slattach started for $DEVICE on $MODEMPORT at $LINESPEED" &)&

	# Check if slattach (or other process) is using $MODEMPORT
	# if not - execute slattach
        if [ -x /usr/sbin/fuser ] && fuser -s $MODEMPORT; then
        logger -p daemon.info -t ifup-sl "some process is currently using $MODEMPORT"
	echo "some process is currently using $MODEMPORT - aborting..."
        else
        slattach -p $PROTOCOL -s $LINESPEED $MODEMPORT &
        usleep 500
	ip link set $DEVICE mtu $MTU up
	ip addr add $IPADDR peer $REMIP dev $DEVICE
# routing chyba jest ustawiany przez g³ówny skrypt ifup ...
#                if [ "$DEFROUTE" = yes ] ; then
#                        route del $REMIP > /dev/null 2>&1
#			ip route add 0.0.0.0/0 dev $DEVICE
#                fi
        fi

fi

