#!/bin/sh
#
#    ifup-lec - ATM LANE interfaces configuration script
#    Copyright (C) 1999, 2000 Robert ¦laski <robin@atm.com.pl>
#    Copyright (C) 2000 Arkadiusz Mi¶kiewicz <misiek@pld.org.pl>
#    Copyright (C) 2000 Jan Rêkorajski <baggins@pld.org.pl>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#    $Id: ifup-lec,v 1.1.2.2 2000/11/04 01:15:08 baggins Exp $
#

. /etc/sysconfig/network
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network-scripts/.functions

DEV=$1

[ -z "$DEV" ] && {
    nls "usage: %s <device name>" ifup-lec >&2
    exit 1
}

if [ -r /etc/sysconfig/atm ]; then
	. /etc/sysconfig/atm
else
	exit 0
fi

if is_no "$LANE"; then
	exit 0
fi

if [ ! -x /sbin/zeppelin ]; then
        nls "%s is missing. Can't continue." "/sbin/zeppelin"
        exit 1
fi
		

if [ -f "/etc/sysconfig/interfaces/ifcfg-$DEV" ] ; then
        CONFIG="/etc/sysconfig/interfaces/ifcfg-$DEV"
else
        CONFIG="$DEV"
fi
		
source_config

if [ "foo$2" = "fooboot" ] && is_no "${ONBOOT}"; then
        exit
fi

# set all major variables
setup_ip_param

# check again in case of manuall interface starting
atm_daemons_start

INTERFACE=$(echo "$DEVICE" | awk ' { gsub(/^lec/,NIL); print $0 } ')

ZOPTS=""
[ -n "$INTERFACE" ] 		&& ZOPTS="$ZOPTS -i $INTERFACE"
[ -n "$LECS_ADDR" ]		&& ZOPTS="$ZOPTS -c $LECS_ADDR"
[ -n "$LES_ADDR" ]		&& ZOPTS="$ZOPTS -s $LES_ADDR"
[ -n "$LEC_MAC" ]		&& ZOPTS="$ZOPTS -e $LEC_MAC"
[ -n "$VLAN_NAME" ]		&& ZOPTS="$ZOPTS -n $VLAN_NAME"
[ -n "$LEC_PHYS" ]		&& ZOPTS="$ZOPTS -I $LEC_PHYS"
[ -n "$LEC_LISTEN_ADDR" ]	&& ZOPTS="$ZOPTS -l $LEC_LISTEN_ADDR"
[ -n "$VLAN_FORESWITCH_NAME" ]	&& ZOPTS="$ZOPTS -f $VLAN_FORESWITCH_NAME"
[ -n "$MTU" ]			&& ZOPTS="$ZOPTS -t $MTU"
[ -n "$ZEPPELIN_DEBUG_MASK" ]	&& ZOPTS="$ZOPTS -m $ZEPPELIN_DEBUG_MASK"
[ -n "$LANE_PROXY" ] && is_yes "$LANE_PROXY" && ZOPTS="$ZOPTS -p"

[ -z "$LANE_VERSION" ] LANE_VERSION="2"
[ "$LANE_VERSION" = "1" ] && ZOPTS="$ZOPTS -1"
[ "$LANE_VERSION" = "2" ] && ZOPTS="$ZOPTS -2"

zeppelin $ZOPTS -F syslog 2>/dev/null &

sleep 1

echo "$!" > /var/run/zeppelin-$DEVICE.pid

if [ -n "$MPOA_CONTROL" -a -n "$MPOA_DATA" -a "$LANE_VERSION" = "2" ] ; then
	mpcd -s $MPOA_CONTROL -l $MPOA_DATA \
	`[ -n "$INTERFACE" ] && echo " -i $INTERFACE"` \
	`[ -n "$VLAN_NAME" ] && echo " -n $VLAN_NAME"` \
	`[ -n "$LEC_ADDR" ] && echo " -L $LEC_ADDR"` \
	`[ -n "$LECS_ADDR" ] && echo " -C $LECS_ADDR"` \
	`[ -n "$MPOA_MPS" ] && echo " -c $MPOA_MPS"` \
	`[ -n "$MPOA_MPS_MAC" ] && echo " -m $MPOA_MPS_MAC"` &
fi

# This must be last line !
# vi:syntax=sh:tw=78:ts=8:sw=4

