#!/bin/sh
#
#	$Id: ifup-plip,v 1.9 1999/10/13 21:28:40 kloczek Exp $
#
PATH=/sbin:/usr/sbin:/bin:/usr/bin

cd /etc/sysconfig/network-scripts
. /etc/sysconfig/network-scripts/.functions

CONFIG=$1
source_config

if [ "foo$2" = "fooboot" -a "${ONBOOT}" = "no" ]
then
	exit
fi

ip -family inet addr add ${IPADDR}/32 peer ${REMIP} dev ${DEVICE}
ip -family inet route add ${NETWORK}/${PREFIX} dev ${DEVICE}

. /etc/sysconfig/network

if [ "${GATEWAY}" != "" ]; then
	if [ "${GATEWAYDEV}" = "" -o "${GATEWAYDEV}" = "${DEVICE}" ]; then
		# set up default gateway
		ip -family inet route add default via ${GATEWAY}
	fi
fi

/etc/sysconfig/network-scripts/ifup-post $1
