#!/bin/sh
#
#    ifup-irda - IrDA configuration script
#    Copyright (C) 2001  Arkadiusz Mi¶kiewicz <misiek@pld-linux.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#    $Id$
#
PATH=/sbin:/usr/sbin:/bin:/usr/bin

cd /etc/sysconfig/network-scripts
. /etc/sysconfig/network
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network-scripts/functions.network

CONFIG=$1
source_config

if [ "foo$2" = "fooboot" ] && is_no "${ONBOOT}"; then
	exit
fi

if [ ! -x /sbin/irattach ]; then
	nls "%s is missing. Can't continue." "/sbin/irattach"
	exit 1
fi

. /etc/sysconfig/network

# set all major variables
setup_ip_param

IRDAOPTS=

if [ -n "${DONGLE}" ]; then
    IRDAOPTS="${IRDAOPTS} -d ${DONGLE}"
fi

if is_yes "${DISCOVERY}" || [ -z "${DISCOVERY}" ]; then
    IRDAOPTS="${IRDAOPTS} -s"
fi

/sbin/irattach ${IRDAPORT} ${IRDAOPTS}
	
ip link set dev ${DEVICE} multicast ${MULTICAST} arp ${ARP}
if ! (ip link set dev ${DEVICE} up); then
	nls "problems with setting %s %s" "IrDA" "${DEVICE}"
	exit 1
fi

# This must be last line !
# vi:syntax=sh:tw=78:ts=8:sw=4

