#!/bin/sh
#
#	$Id: ifup-ipx,v 1.8 2000/04/03 14:50:47 baggins Exp $
#
# configures IPX on $1 if appropriate

PATH=/sbin:/usr/sbin:/bin:/usr/bin

if [ "$1" = "" ]; then
	echo "usage: $0 <net-device>"
	exit 1
fi

if [ ! -x /usr/bin/ipx_interface ] ; then
	# cannot configure IPX with non-existant utilities
	exit 0
fi

. /etc/sysconfig/network

case $IPX in yes|true) ;; *) exit 0 ;; esac

cd /etc/sysconfig/network-scripts
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network-scripts/.functions

CONFIG=$1
[ -f "$CONFIG" ] || CONFIG=ifcfg-$CONFIG
source_config

case $IPXPRIMARY in
    yes|true) primary=-p ;;
    *) primary= ;;
esac

ip link set $DEVICE up
/usr/bin/ipx_interface add $DEVICE $primary $IPXFRAMETYPE $IPXNETWORK

exit 0

