#!/bin/sh
#
#	$Id$
#
# adds static arps for device $DEVICE

if [ ! -f /etc/sysconfig/static-arp ]; then
	return
fi

# note the trailing white space character in the grep gets rid of aliases
egrep "^($DEVICE|any)[[:blank:]]" /etc/sysconfig/static-arp | while read iface mac ip state args; do
	if is_no "$IPV4_NETWORKING"; then
		continue
	fi
	[ -z "$state" ] && state="stale"
	/sbin/ip neigh replace $ip lladdr $mac nud $state dev $DEVICE
done

# This must be last line !
# vi:syntax=sh
