#!/bin/sh
#
#	$Id: ifup-plip,v 1.11 2001/02/23 18:06:48 baggins Exp $
#
PATH=/sbin:/usr/sbin:/bin:/usr/bin

CONFIG=$1
. /etc/sysconfig/network
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network-scripts/.functions

source_config

if [ "foo$2" = "fooboot" ] && is_no "${ONBOOT}"; then
	exit
fi

ip link set ${DEVICE} up
ip -family inet addr add ${IPADDR}/32 peer ${REMIP} dev ${DEVICE}
ip -family inet route add ${NETWORK}/${PREFIX} dev ${DEVICE}

if [ "${GATEWAY}" != "" ]; then
	if [ "${GATEWAYDEV}" = "" -o "${GATEWAYDEV}" = "${DEVICE}" ]; then
		# set up default gateway
		ip -family inet route add default via ${GATEWAY}
	fi
fi

/etc/sysconfig/network-scripts/ifup-post $1
