#!/bin/sh
#
#	$Id: ifup-post,v 1.11 1999/09/28 16:17:30 jajcus Exp $
#

cd /etc/sysconfig/network-scripts
. /etc/sysconfig/network
. /etc/rc.d/init.d/functions.network

need_hostname
CONFIG=$1
source_config

# pelna nazwa dewajsa jaka podal user
FULLDEVNAME="$DEVICE"
# przyjmuje warto¶æ np: "dummy" czy "eth" itd.
DEVICETYPE=`echo $FULLDEVNAME | sed "s/[0-9]*$//"`
# przyjmuje eth0 przy {eth0,eth0:1,eth0:alias}
DEVICE=`echo $FULLDEVNAME | sed 's/:.*//g'`

if echo "$FULLDEVNAME" | grep -q ':' ; then
    ISALIAS=yes
else
    ISALIAS=no
fi

/etc/sysconfig/network-scripts/ifup-routes ${FULLDEVNAME}

if [ "$ISALIAS" == "no" ] ; then
    /etc/sysconfig/network-scripts/ifup-aliases ${DEVICE}
fi

# don't set hostname on ppp/slip connections
if [ -n "$NEEDHOSTNAME" -a "${DEVICE}" != lo -a "${DEVICETYPE}" != "ppp" -a "${DEVICETYPE}" != "slip" ]; then
     IPADDR=`ip addr show dev ${DEVICE} label ${FULLDEVNAME} | 
	    awk '{ print $2 }' |awk -F"/" '{ print $1 }'`
    eval `/bin/ipcalc --silent --hostname ${IPADDR}` && set_hostname $HOSTNAME
fi

# Notify programs that have requested notification
do_netreport

exit 0
