#!/bin/sh
#
#    ifup-atm - ATM CLIP interfaces configuration script
#    Copyright (C) 1999, 2000 Robert ¦laski <robin@atm.com.pl>
#    Copyright (C) 2000 Arkadiusz Mi¶kiewicz <misiek@pld.org.pl>
#    Copyright (C) 2000 Jan Rêkorajski <baggins@pld.org.pl>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#    $Id: ifup-atm,v 1.1.2.3 2001/09/30 10:19:42 misiek Exp $
#

. /etc/sysconfig/network
. /etc/rc.d/init.d/functions
. /etc/sysconfig/network-scripts/functions.network

DEV=$1

[ -z "$DEV" ] && {
    nls "usage: %s <device name>" "ifup-atm" >&2
    exit 1
}

if [ -r /etc/sysconfig/atm ]; then
	. /etc/sysconfig/atm
else
	exit 0
fi

if is_no "$CLIP"; then
	exit 0
fi

if [ ! -x /sbin/atmarp ]; then
        nls "%s is missing. Can't continue." "/sbin/atmarp"
        exit 1
fi
		

if [ -f "/etc/sysconfig/interfaces/ifcfg-$DEV" ] ; then
        CONFIG="/etc/sysconfig/interfaces/ifcfg-$DEV"
else
        CONFIG="$DEV"
fi
		
source_config

if [ "foo$2" = "fooboot" ] && is_no "${ONBOOT}"; then
        exit
fi

# set all major variables
setup_ip_param

# check again in case of manuall interface starting
atm_daemons_start

atmarp -c $DEVICE

# This just will not work, IP setup must be done before atmarp -s :(
AAOPTS=""
DQOPTS=""
[ -n "$ATMARP_DEFAULT_QOS" ]	&& DQOPTS="$DQOPTS qos $ATMARP_DEFAULT_QOS"
[ -n "$ATMARP_DEFAULT_SNDBUF" ]	&& DQOPTS="$DQOPTS sndbuf $ATMARP_DEFAULT_SNDBUF"
[ -n "$ATMARP_QOS" ]		&& AAOPTS="$AAOPTS qos $ATMARP_QOS"
[ -n "$ATMARP_SNDBUF" ]		&& AAOPTS="$AAOPTS sndbuf $ATMARP_SNDBUF"
[ -n "$ATMARP_TEMP" ] && is_yes "$ATMARP_TEMP"	&& AAOPTS="$AAOPTS temp"
[ -n "$ATMARP_PUB" ]  && is_yes "$ATMARP_PUB"	&& AAOPTS="$AAOPTS pub"

if [ -n "$ARPSRV_ATMADDR" ] ; then
	if is_no "$ATMARP_SERVER" ; then
		atmarp -s $NETWORK $ARPSRV_ATMADDR $AAOPTS arpsrv
	fi
else
	atmarp -s $ATMARP_REMIP $ATMARP_PVC $AAOPTS \
		`[ -n "$ATMARP_NULL" ] && is_yes "$ATMARP_NULL" && echo null`
fi

if [ -n "$DQOPTS" ] ; then
	atmarp -q $DQOPTS
fi

# This must be last line !
# vi:syntax=sh:tw=78:ts=8:sw=4

