#!/bin/sh
#
#	$Id: tnlup,v 1.7 1999/07/31 11:24:20 misiek Exp $
#
# Author: Arkadiusz Mi¶kiewicz <misiek@pld.org.pl>
#
# Uwagi:
# - przy dodawaniu routingu w ifup pamiêtac o "onlink" (patrz dokumentacja do iproute)
#

cd /etc/sysconfig/network-scripts
. /etc/rc.d/init.d/functions.network
. /etc/sysconfig/network

CONFIG=$1

[ -z "$CONFIG" ] && {
    echo "usage: tnlup <device name>" >&2
    exit 1
}

[ -f "/etc/sysconfig/interfaces/$CONFIG" ] || CONFIG=tnlcfg-$CONFIG
[ -f "/etc/sysconfig/interfaces/$CONFIG" ] || {
    echo "usage: tnlup <device name>" >&2
    exit 1
}

source_config

if [ "foo$2" = "fooboot" -a "${ONBOOT}" = "no" ]
then
        exit
fi

if [ "$IPV6_TUNNELCONFIG" != "yes" ] && [ "$MODE" == "sit" ] ||
   [ "$IPX" != "yes" ] && [ "$MODE" == "ipxip" ] || [ "$IPX" != "yes" ] && [ "$MODE" == "ipipx" ]
then
	exit
fi

[ -z "${TTL}" ] && TTL=64
[ -z "${TOS}" ] && TOS=inherit
[ -z "${LOCALADDR}" ] && LOCALADDR=any
[ -z "${REMOTEADDR}" ] && REMOTEADDR=any
[ -n "${BIND_DEV}" ] && BIND_DEV="dev $BIND_DEV"

if [ "${SEQ}" == "yes" ]; then
	SEQ=seq
else
	[ "${ISEQ}" == "yes" ] && SEQ=iseq
	[ "${OSEQ}" == "yes" ] && SEQ="$SEQ oseq"
fi

if [ "${CSUM}" == "yes" ]; then
	CSUM=csum
else
        [ "${ICSUM}" == "yes" ] && CSUM=icsum
        [ "${ICSUM}" == "yes" ] && CSUM="$SEQ ocsum"
fi

[ "${ISEQ}" == "yes" ] && ISEQ=iseq
[ "${ISEQ}" == "yes" ] && ISEQ=iseq
[ "${ISEQ}" == "yes" ] && ISEQ=iseq
[ "${ISEQ}" == "yes" ] && ISEQ=iseq

[ "${TTL}" != "0" -a "${TTL}" != "inherit" ] && PMTUDISC=yes

if [ "${PMTUDISC}" == "yes" ]; then
	PMTUDISC=pmtudisc
else
	PMTUDISC=nopmtudisc
fi

if [ -n "${KEY}" ]; then
IKEY=""
OKEY=""
fi

if [ "${MODE}" == "ipip" ] || [ "${MODE}" == "sit" ]; then
	
	ip tunnel add ${DEVICE} mode ${MODE} local ${LOCALADDR} remote ${REMOTEADDR} ttl ${TTL} tos ${TOS} ${PMTUDISC} ${BIND_DEV}

elif [ "${MODE}" == "gre" ]; then

	ip tunnel add ${DEVICE} mode ${MODE} local ${LOCALADDR} remote ${REMOTEADDR} ttl ${TTL} tos
${TOS} ${PMTUDISC} ${BIND_DEV} $CSUM $ISEQ ${KEY} ${IKEY} ${OKEY}

elif [ "${MODE}" == "ipxip" ] || [ "${MODE}" == "ipipx" ]; then

echo "obs³uga ipxip jeszcze nie zrobiona"

fi
