#!/bin/sh
#
# halt          Script for system halt.
#
# chkconfig: 0 00 99
# description:	This file is executed by init when it goes into runlevel \
#               runlevel 0 (halt). It calls common code for halt/reboot \
#		from shutdwn which kills all processes, unmounts file  \
#		systems and then either halts or reboots.
#
# Author:       Grzegorz Stanislawski <stangrze@open.net.pl>
# Changes:	Arkadiusz Mi¶kiewicz <misiek@pld.org.pl>
#
# $Id: halt,v 1.4 1999/07/31 11:24:19 misiek Exp $

# NLS
NLS_DOMAIN="rc-scripts"

# See how we were called.

. /etc/rc.d/init.d/functions

case "$1" in
  stop*)
	exit 0
	;;
  start*)
	. /etc/rc.d/init.d/shutdwn
        show "The system is halted"; ok
	[ -f /fastboot ] && (show "On the next boot fsck will be skipped."; ok)
	eval halt -d
	;;
esac
