#!/bin/sh
# 
# killall        Script for system downing
#
# description:   kill em all
#
# $Id: killall,v 1.6 1999/10/13 16:11:27 baggins Exp $
# Bring down all unneeded services that are still running (there shouldn't 
# be any, so this is just a sanity check)

case "$1" in
  start*)
        exit 0
        ;;
  stop*)
	for i in /var/lock/subsys/*; do
		# Check if the script is there.
		[ ! -f $i ] && continue
	
		# Get the subsystem name.
		subsys=${i#/var/lock/subsys/}
	
		# Bring the subsystem down.
		if [ -f /etc/rc.d/init.d/$subsys.init ]; then
			/etc/rc.d/init.d/$subsys.init stop
		else
			/etc/rc.d/init.d/$subsys stop
		fi
	done
	;;
esac
