#!/bin/sh
#
# local	Invoke custom scripts at startup
# chkconfig:	2345 99 01
#
# description:	This script will be executed *after* all the other init \
# scripts. You can put your own initialization stuff in here if you don't \
# want to do the full Sys V style init stuff.
#
# $Id$

# First set up a default search path.
export PATH="/sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin"

# See how we were called.
case "$1" in
  start)
	  touch /var/lock/subsys/local
	  . /etc/rc.d/rc.local
	;;
  stop)
	  rm -f /var/lock/subsys/local
	;;
  *)
	msg_usage "$0 {start|stop}"
	exit 3
esac

exit 0
