#!/bin/sh
#
# netfs         Mount network filesystems.
#
# Authors:	Bill Nottingham <notting@redhat.com>
# 		Miquel van Smoorenburg, <miquels@drinkel.nl.mugnet.org>
#
# chkconfig: 345 15 85
# description: Mounts and unmounts all Network File System (NFS), \
#	       SMB (Lan Manager/Windows), and NCP (NetWare) mount points.
#
# $Id: netfs,v 1.2 1999/07/31 11:24:19 misiek Exp $

# Source networking configuration.
if [ ! -f /etc/sysconfig/network ]; then
    exit 0
fi

# NLS
NLS_DOMAIN="rc-scripts"

# Source function library.
. /etc/rc.d/init.d/functions

. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

NFSFSTAB=`grep -v '^#' /etc/fstab | awk '{ if ($3 ~ /^nfs$/ && $4 !~ /noauto/) print $2}'`
SMBFSTAB=`grep -v '^#' /etc/fstab | awk '{ if ($3 ~ /^smbfs$/ && $4 !~ /noauto/) print $2}'`
NCPFSTAB=`grep -v '^#' /etc/fstab | awk '{ if ($3 ~ /^ncpfs$/ && $4 !~ /noauto/) print $2}'`
NFSMTAB=`grep -v '^#' /proc/mounts | awk '{ if ($3 ~ /^nfs$/ && $4 !~ /noauto/) print $2}'`
SMBMTAB=`grep -v '^#' /proc/mounts | awk '{ if ($3 ~ /^smbfs$/ && $4 !~ /noauto/) print $2}'`
NCPMTAB=`grep -v '^#' /proc/mounts | awk '{ if ($3 ~ /^ncpfs$/ && $4 !~ /noauto/) print $2}'`

# See how we were called.
case "$1" in
  start)
        [ -n "$NFSFSTAB" ] && run_cmd "Mounting NFS filesystems" mount -a -t nfs
        [ -n "$SMBFSTAB" ] && run_cmd "Mounting SMB filesystems" mount -a -t smbfs
        [ -n "$NCPFSTAB" ] && run_cmd "Mounting NCP filesystems" mount -a -t ncpfs
	touch /var/lock/subsys/netfs
	run_cmd "Mounting other filesystems" mount -a
	;;
  stop)
	[ -n "$NFSMTAB" ] && run_cmd "Unmounting NFS filesystems" umount -a -t nfs
	[ -n "$SMBMTAB" ] && run_cmd "Unmounting SMB filesystems" umount -a -t smbfs
	[ -n "$NCPMTAB" ] && run_cmd "Unmounting NCP filesystems" umount -a -t ncpfs
	rm -f /var/lock/subsys/netfs
	;;
  status)
	if [ -f /proc/mounts ] ; then
	        [ -n "$NFSFSTAB" ] && {
		     nls "Configured NFS mountpoints:"
		     for fs in $NFSFSTAB; do echo $fs ; done
		}
	        [ -n "$SMBFSTAB" ] && {
		     nls "Configured SMB mountpoints:"
		     for fs in $SMBFSTAB; do echo $fs ; done
		}
	        [ -n "$NCPFSTAB" ] && {
		     nls "Configured NCP mountpoints:"
		     for fs in $NCPFSTAB; do echo $fs ; done
		}
		[ -n "$NFSMTAB" ] && {
                      nls "Active NFS mountpoints:"
		      for fs in $NFSMTAB; do echo $fs ; done
		}
		[ -n "$SMBMTAB" ] && {
                      nls "Active SMB mountpoints:"
		      for fs in $SMBMTAB; do echo $fs ; done
		}
		[ -n "$NCPMTAB" ] && {
                      nls "Active NCP mountpoints:"
		      for fs in $NCPMTAB; do echo $fs ; done
		}
	else
		nls "/proc filesystem unavailable"
	fi
	;;
  restart)
	$0 stop
	$0 start
	;;
  reload)
        $0 start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac

exit 0

