#!/bin/sh
#
# network       Bring up/down networking
#
# chkconfig: 2345 10 90
# description: Activates/Deactivates all network interfaces configured to \
#              start at boot time.
# probe: true

# $Id: network,v 1.15 1999/08/04 16:59:01 baggins Exp $

# NLS
NLS_DOMAIN="rc-scripts"

# Source function library.
. /etc/rc.d/init.d/functions
. /etc/rc.d/init.d/functions.network

[ ! -f /etc/sysconfig/network ] && exit 0

. /etc/sysconfig/network

# Check that networking is up.
[ "${NETWORKING}" == "no" -o "${NETWORKING}" == "" ] && exit 0

[ -x /sbin/ip ] || exit 0

######
# initialize networking:
# - check IPv4, IPv6, IPX can be handled by system
# - setup default IPv{4,6} interfaces policy like:
#   - forwarding,
#   - spoofig protection,
#   - icmp echo ignore broadcasts,
# - setup lo interface
network_init()
{
# Set UP loopback interface
set_up_loopback

# Modprobe needed devices
modprobe_net

# Set static ARP table
static_arp

# Spoofing protection
ipv4_anti_spoofing on

# IPv4 forwarding
proc_net ipv4/ip_forward start 1 0 $IPV4_FORWARDING "IPv4 forwarding"

# IPv6 forwarding
proc_net ipv6/conf/all/forwarding start 1 0 $IPV6_FORWARDING "IPv6 forwarding"

}

######
# deinitialize networking
# - down lo interface.
network_deinit()
{

# IPv6 forwarding
proc_net ipv6/conf/all/forwarding stop 1 0 $IPV6_FORWARDING "IPv6 forwarding"

# IPv4 forwarding
proc_net ipv4/ip_forward stop 1 0 $IPV4_FORWARDING "IPv4 forwarding"

# Spoofing protection
ipv4_anti_spoofing off

# Set DOWN loopback interface
set_down_loopback
}

# Normal sort order
interfaces_up="`(cd /etc/sysconfig/interfaces && ls -1 ifcfg-* | \
grep -v ifcfg-lo | xargs ) 2> /dev/null`"
# Reverse sort order
interfaces_down="`(cd /etc/sysconfig/interfaces && ls -r -1 ifcfg-* | \
grep -v ifcfg-lo | xargs ) 2> /dev/null`"
# Normal sort order
tunnels="`(cd /etc/sysconfig/interfaces && ls -1 tnlcfg-* | xargs ) 2> /dev/null`"

# See how we were called.
case "$1" in
  start)
	network_init
	for i in $tunnels; do
		[ -f /etc/sysconfig/interfaces/$i ] && /sbin/tnlup $i boot
	done

	for i in $interfaces_up; do
		[ -f /etc/sysconfig/interfaces/$i ] && /sbin/ifup $i boot
	done

        touch /var/lock/subsys/network
        ;;
  stop)
	for i in $interfaces_down; do
		[ -f /etc/sysconfig/interfaces/$i ] && /sbin/ifdown $i boot
	done

	for i in $tunnels; do
                [ -f /etc/sysconfig/interfaces/$i ] && /sbin/tnldown $i boot
        done

	network_deinit
        rm -f /var/lock/subsys/network
        ;;
  status)
	nls "Configured devices:"
	echo "lo $interfaces"
	nls "Configured tunnels:"
	echo "$tunnels"

	nls "Currently active devices:"
	/sbin/ip link show | egrep '^[^ ].*' |sed 's/[0-9]*: \(.*\):.*/\1/'|xargs
	;;
  restart)
	$0 stop
	$0 start
	;;
  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
