#!/bin/sh
#
# reboot          Script for system halt/reboot.
#
# chkconfig: 6 00 00
# description:	This file is executed by init when it goes into runlevel \
#               runlevel 6 (reboot). It calls common code for halt/reboot \
#		from shutdwn which kills all processes, unmounts file  \
#		systems and then either halts or reboots.
#
# Author:       Grzegorz Stanislawski <stangrze@open.net.pl>
#

# See how we were called.
case "$1" in
  stop*)
	exit 0
	;;
  start*)
	. /etc/rc.d/init.d/shutdwn
	echo "Please stand by while rebooting the system..."
	[ -f /fastboot ] && echo "On the next boot fsck will be skipped."
	eval reboot -d
	;;
esac
