#!/bin/sh
#
# shutdwn       Common script for system halt/reboot.
#
# Author:       Miquel van Smoorenburg, <miquels@drinkel.nl.mugnet.org>
#               Modified for PLD Linux by Grzegorz Stanislawski
# Changes:      Arkadiusz Mi¶kiewicz <misiek@pld.org.pl>
#

# Set the path.
PATH=/sbin:/bin:/usr/bin:/usr/sbin

. /etc/rc.d/init.d/functions

# Kill all processes.
[ "${BASH+bash}" = bash ] && enable kill

show "Sending all processes the TERM signal "
daemon killall5 -15
sleep 5
show "Sending all processes the KILL signal "
daemon killall5 -9

# Write to wtmp file before unmounting /var
halt -w

# Turn off swap, then unmount file systems.
run_cmd "Turning off swap and accounting" swapoff -a
[ -x /sbin/accton ] && /sbin/accton
run_cmd "Unmounting file systems" umount -a
run_cmd "Remounting root filesystem in ro mode" mount -n -o remount,ro /

# turn off raid
if [ -x /sbin/raidstop -a -f /etc/raidtab ]; then
	# we can not use raidstop -a here because this will only stop
	# devices listed in the default config file which is not always
	# the case. So we look only for the active raid devices
	if [ -f /proc/mdstat ] ; then
		mddevs=$(grep ^md /proc/mdstat | awk '{ print $1 }')
		for mddev in $mddevs ; do
			run_cmd "Turning off RAID for $mddev" raidstop /dev/$mddev
		done
		unset mddev mddevs
	fi
	#runcmd "Turning off RAID" /sbin/raidstop -a
fi

show "Remounting remaining filesystems ro mode"; busy
if (mount | awk '/ext2/ { print $3 }' | \
	while read line; do 
		mount -n -o ro,remount $line done); then
	deltext; ok
else
	deltext; fail
fi
