#!/bin/sh
#
# You can put here anything :)
#
echo " Roz³±czenie o `date` z $PPP_REMOTE                    " >> /var/log/ppp.log
echo "+---------------------------------------------------------------+" >> /var/log/ppp.log
