#!/bin/sh
# $Id: logger,v 1.1 2000/05/07 19:00:03 siefca Exp $
# You can put here anything :)
#
echo " Disconnect time: `date` from $PPP_REMOTE                    " >> /var/log/ppp.log
echo "+---------------------------------------------------------------+" >> /var/log/ppp.log
