#!/bin/sh
# $Id: logger,v 1.4 1999/07/31 11:24:18 misiek Exp $
# You can put here anything :)
#
echo "+---------------------------------------------------------------+" >> /var/log/ppp.log
echo " Connect time: `date` with $PPP_REMOTE                    " >> /var/log/ppp.log
