#!/bin/sh
#
# You can put here anything :)
#
echo "+---------------------------------------------------------------+" >> /var/log/ppp.log
echo " Conect time: `date` z $PPP_REMOTE                    " >> /var/log/ppp.log
